### ISSUE TITLE
Make install fails with error about python module

### ISSUE THREAD

**Issue by jwilms1971** [hybrid-cloud-patterns/multicloud-gitops#98]
Is there some prerequisites missing? I am running this from RHEL8.6.

$ make install
make -f common/Makefile deploy
make[1]: Entering directory '/home/jwilms/code/multicloud-gitops'
Checking repo https://github.com/jwilms1971/multicloud-gitops.git - branch main
https://github.com/jwilms1971/multicloud-gitops.git - main exists
helm upgrade --install multicloud-gitops common/install/ -f values-global.yaml --set main.git.repoURL="https://github.com/jwilms1971/multicloud-gitops.git" --set main.git.revision=main --set global.hubClusterDomain=apps.hub-cluster-1.aws.jwilms.net
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/jwilms/clusters/hub-cluster-1/auth/kubeconfig
Release "multicloud-gitops" does not exist. Installing it now.
I0718 11:29:54.700962  120604 request.go:601] Waited for 1.179609528s due to client-side throttling, not priority and fairness, request: GET:https://api.hub-cluster-1.aws.jwilms.net:6443/apis/network.operator.openshift.io/v1?timeout=32s
NAME: multicloud-gitops
LAST DEPLOYED: Mon Jul 18 11:30:00 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
make[1]: Leaving directory '/home/jwilms/code/multicloud-gitops'
make[1]: Entering directory '/home/jwilms/code/multicloud-gitops'
make -f common/Makefile vault-init
make[2]: Entering directory '/home/jwilms/code/multicloud-gitops'
common/scripts/vault-utils.sh vault_init common/pattern-vault.init

PLAY [Vault initialization] ***********************************************************************************************************************************

TASK [vault_utils : include_tasks] ****************************************************************************************************************************
included: /home/jwilms/code/multicloud-gitops/common/ansible/roles/vault_utils/tasks/pre_check.yaml for localhost

TASK [vault_utils : Check if the kubernetes python module is usable from ansible] *****************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["/usr/bin/python3.8", "-c", "import kubernetes"], "delta": "0:00:00.011533", "end": "2022-07-18 11:30:03.800305", "msg": "non-zero return code", "rc": 1, "start": "2022-07-18 11:30:03.788772", "stderr": "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nModuleNotFoundError: No module named 'kubernetes'", "stderr_lines": ["Traceback (most recent call last):", "  File \"<string>\", line 1, in <module>", "ModuleNotFoundError: No module named 'kubernetes'"], "stdout": "", "stdout_lines": []}

PLAY RECAP ****************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

make[2]: *** [common/Makefile:61: vault-init] Error 2
make[2]: Leaving directory '/home/jwilms/code/multicloud-gitops'
make[1]: *** [Makefile:10: vault-init] Error 2
make[1]: Leaving directory '/home/jwilms/code/multicloud-gitops'
make: *** [Makefile:13: install] Error 2

**Comment by beekhof** [comment]
@mbaldessari I thought vault-init was no longer needed from the makefile

**Comment by mbaldessari** [comment]
> @mbaldessari I thought vault-init was no longer needed from the makefile

Only if you set "clusterGroup.insecureUnsealVaultInsideCluster: true" in your values-hub file. But even then you'll need the requirements for running 'make load-secrets'

@jwilms1971 Thanks for the report. I'll make sure these are checked and documented. In the meantime they are:
- helm
- oc
- make
- ansible + kubernetes.core (collection)

**Comment by mbaldessari** [comment]
Ok so with the common/ update in multicloud-gitops I just did, there is a prereq check that will verify this things.

I will close this now. Thanks for the report!
