### ISSUE TITLE
from-secret should use protect-function

### ISSUE THREAD

**Issue by ch-stark** [hybrid-cloud-patterns/multicloud-gitops#99]
refering to:

https://github.com/hybrid-cloud-patterns/multicloud-gitops/blob/73415854a8b2abfa335a3aa3c9cd152cd7e7904d/charts/all/config-demo/templates/config-demo-secret.yaml

Note that this is a secure way of copying the secrets when using ACM 2.5.  Prior to ACM 2.5 you would have likely used a Namespace Channel, but that feature is no longer available.  The ACM 2.5 doc on securely copying hub data to managed clusters is here: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/governance/governance#protect-function

**Comment by mbaldessari** [comment]
Thanks @ch-stark . Given that we use fromSecret the '| protect' call is automatically done for us, correct? I.e. we only need to add '| protect' in the places we do not use hub + fromSecret, right?
